name: funky_new
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  camerawesome: ^2.1.0
  get: ^4.6.1
  hexcolor: ^3.0.1

  fluttertoast: ^8.0.8

  cloud_firestore: ^5.6.2

  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1
  firebase_auth: ^5.4.1
  flutter_local_notifications: ^18.0.1
  flutter_facebook_auth: ^7.1.1

  google_sign_in: ^6.2.1
  twitter_login: ^4.0.1
  webview_flutter: ^4.10.0
  get_storage: ^2.0.3
  flutter_staggered_grid_view: ^0.4.0
  loading_indicator: ^3.0.2
  video_player: ^2.2.18
  pinput: ^4.0.0
  dropdown_button2: ^2.3.9
  searchfield: ^1.0.4
  circle_list: ^1.0.5
  visibility_detector: ^0.4.0+2
  video_compress: ^3.1.3

  image_picker: ^1.0.8
  shared_preferences: ^2.5.1
  flutter_launcher_icons: ^0.14.3

  qr_flutter: ^4.0.0
  qr_code_scanner_plus: ^2.0.9+1

  camera: ^0.10.5+9

  video_thumbnail: ^0.5.3
  path_provider: ^2.0.9
  drag_ball: ^2.0.0
  fading_edge_scrollview: ^4.1.1

  video_editor: ^3.0.0
  #  helpers: ^1.2.3

  cached_network_image: ^3.4.1
  readmore: ^3.0.0
  share_plus: ^7.2.2
  flutter_countdown_timer: ^4.1.0

  google_fonts: ^4.0.4

  provider: ^6.0.2
  image: ^4.5.2
  photo_view: ^0.14.0

  #  image_gallery_saver: ^2.0.3
  # position
  align_positioned: ^3.0.0
  # own packages
  # gallery_media_picker: ^0.1.0
  modal_gif_picker:
  # painting
  perfect_freehand: ^1.0.4
  # animations
  animated_text_kit: ^4.2.1
  # rendering
  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  # permission
  permission_handler: ^11.3.1
  marquee: ^2.2.3
  gallery_saver_plus: ^3.2.1
  dio: ^5.4.3+1
  file_picker: ^8.3.1
  syncfusion_flutter_pdfviewer: ^28.2.3
  open_file: ^3.2.1
  #  quickblox_sdk: ^0.6.1-beta
  rxdart: ^0.28.0
  #  provider: ^6.0.0

  #  hive_flutter: ^1.1.0
  hive: ^2.1.0
  build_runner: ^2.1.11
  #  package_info: ^2.0.2
  package_info_plus: ^8.1.4
  flutter_svg: ^2.0.9
  # quickblox_sdk: ^0.14.2

  intl: ^0.19.0
  grouped_list: ^5.1.1
  connectivity_plus: ^6.1.2
  url_launcher: ^6.1.5
  mime: ^1.0.2
  #  audioplayers: ^0.20.1
  just_audio: ^0.9.31
  audio_session: ^0.1.11

  flutter_audio_waveforms: ^1.2.1+6
  image_cropper:
  http:
  css_filter: ^1.0.2
  flutter_app_badge_control: ^0.0.2
  telegram: ^0.0.3
  #  flutter_sms: ^2.3.3
  flutter_email_sender: ^6.0.3
  flutter_media_metadata: ^1.0.0+1

  #image Editors

  zoom_widget: ^2.0.0
  font_awesome_flutter: ^10.1.0

  screenshot: ^3.0.0
  flutter_colorpicker: ^1.0.3
#  nb_utils: ^7.1.0
  # extended_image: ^7.0.0
  crop: ^0.5.2
  image_editor: ^1.0.2
  colorfilter_generator: ^0.0.8
  hand_signature: ^3.0.3
  #  image_compression_flutter: ^1.0.4
  flutter_image_compress: ^2.4.0
  simple_html_css: ^5.0.0
  photo_manager: ^3.6.4
  uuid: ^4.5.1
  #  flutter_ringtone_player: ^4.0.0+3
  socket_io_client: ^2.0.3+1
  bloc: ^8.1.4
  flutter_bloc: ^8.0.1
  modal_progress_hud_nsn: ^0.5.1
  audioplayers: ^5.2.1
  conditional_builder_null_safety: ^0.0.6
  quiver: ^3.1.0
  # agora_uikit: ^1.3.10
  agora_rtc_engine: ^6.5.0
  googleapis_auth: ^1.4.1
  flutter_stripe: ^11.4.0
  stripe_android: ^11.4.0
  gal: ^2.3.1

  # open_filex: ^4.4.0

  webview_flutter_android: ^4.3.1
  webview_flutter_wkwebview: ^3.18.0
  sms_mms: ^0.0.3
  firebase_core: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
dependency_overrides:
  #  firebase_core_platform_interface:
  http:

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/

    #   - images/a_dot_ham.jpeg

  fonts:
    - family: PB
      fonts:
        - asset: assets/fonts/Product Sans Bold.ttf
    - family: PBI
      fonts:
        - asset: assets/fonts/Product Sans Bold Italic.ttf
    - family: PI
      fonts:
        - asset: assets/fonts/Product Sans Italic.ttf
    - family: PR
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf

    - family: POPB
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: POPL
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: POPM
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: POPR
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: POPSB
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: customHeart
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya-VariableFont_wght.ttf

    - family: B612
      fonts:
        - asset: assets/fonts/B612-Regular.ttf

    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf

    - family: Varela
      fonts:
        - asset: assets/fonts/Varela-Regular.ttf

    - family: Vollkorn
      fonts:
        - asset: assets/fonts/Vollkorn-Regular.ttf

    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas-Regular.ttf

    - family: ConcertOne
      fonts:
        - asset: assets/fonts/ConcertOne-Regular.ttf

    - family: YatraOne
      fonts:
        - asset: assets/fonts/YatraOne-Regular.ttf

    - family: OldStandardTT
      fonts:
        - asset: assets/fonts/OldStandardTT-Italic.ttf

    - family: Neonderthaw
      fonts:
        - asset: assets/fonts/Neonderthaw-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf

    - family: SedgwickAve
      fonts:
        - asset: assets/fonts/SedgwickAve-Regular.ttf

    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf

    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf

    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

    - family: FrederickatheGreat
      fonts:
        - asset: assets/fonts/FrederickatheGreat-Regular.ttf

    - family: ReenieBeanie
      fonts:
        - asset: assets/fonts/ReenieBeanie-Regular.ttf

    - family: BungeeShade
      fonts:
        - asset: assets/fonts/BungeeShade-Regular.ttf

    - family: UnifrakturMaguntia
      fonts:
        - asset: assets/fonts/UnifrakturMaguntia-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
